### ISSUE TITLE
Rounding of the longitude/latitude of the float to the database will loose exact GPS location

### ISSUE THREAD

**Issue by joelvdgraaf** [mendix/GoogleMapsModule#1]
A longitude and/or latitude can have 15 decimals behind the comma to have the precise location of the address. Only the module uses floats for those attributes. The issue is that when saving the data to the database a lot of the decimals are just chopped away. For example from 15 decimals to 7 decimals.

Please change the attributes longitude and latitude to String so that the decimal precision still be correct.

**Comment by RoelandSalij** [comment]
Do you have an example address where you experience this behaviour?

**Comment by JelteMX** [comment]
The widget has the ability to use Strings as lat an long attributes: https://github.com/mendix/GoogleMapsWidget/blob/master/src/GoogleMaps/GoogleMaps.xml#L96
