### ISSUE TITLE
Insecure loading of google library

### ISSUE THREAD

**Issue by mrgroen** [mendix/GoogleMapsModule#2]
The Google library is loaded insecure which causes an error and prevents the widget from loading.
Locally it will work but in a live Mendix Node (or sandbox) environment the error will be thrown by the browser because it tries to load http over https.

I would advise to check and use the correct protocol.

Kind regards, Marcus

**Comment by JelteMX** [comment]
Could you check if my fixed version of the Google Maps Widget (part of the module) might do the trick? Download [GoogleMaps.mpk](https://github.com/mendix/GoogleMapsWidget/raw/bugfix/unsecure-loading/test/widgets/GoogleMaps.mpk) and see if that works.

We fixed that particular issue a few months ago. I updated the included Google JsAPI that loads Google Maps.

**Comment by JelteMX** [comment]
Fixed in [5.2.1](https://github.com/mendix/GoogleMapsModule/releases/tag/v5.1.2)
