### ISSUE TITLE
Default latitude and longitude 

### ISSUE THREAD

**Issue by AnniekJose** [mendix/GoogleMapsModule#3]
Hi, maybe I'm overlooking something, but I can't seem to get the default latitude and longitude right. I want the card to open on the netherlands. I set the latitude to 52.3702160 and the longitude to 4.8951680, which should be Amsterdam according to http://nl.mygeoposition.com/, but it still opens Google maps at a random place at sea, in the golf of guinnee. Can someone tell me what I am doing wrong?

**Comment by JelteMX** [comment]
Have you set this as the default Lat and Lon? (See [documentation](https://github.com/mendix/GoogleMapsWidget#properties))

**Comment by AnniekJose** [comment]
Yes I did.

**Comment by JelteMX** [comment]
I might need a testproject to check this, as far as I know it works. Will look into it later on. If I can't reproduce the issue in our own test-project, I will ask you to send one to community [at] mendix.com

**Comment by RoelandSalij** [comment]
Hi AnniekJose,
Are you trying this in 
 - a custom project or,
-  in the GoogleMaps Module repository(this one) or,
-  the Google Maps widget repository? 

This repository, Google Maps **Module**, has functionality to calculate the geolocation based on an address so I guess you aren't having this problem there.

I've update the Google Maps **Widget** repository so it has an update button and will save your changes to the object.

In case you try it in a custom project, make sure you set the 'pan to context' property to **Yes**.

**Comment by RoelandSalij** [comment]
@AnniekJose, is your issue resolved?

**Comment by AnniekJose** [comment]
Hey, sorry, yes it is resolved :) Thanks for your help!
